package agentpb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/agent.proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignedId    string                 `protobuf:"bytes,1,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StartedUnix   int64                  `protobuf:"varint,2,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	NowUnix       int64                  `protobuf:"varint,3,opt,name=now_unix,json=nowUnix,proto3" json:"now_unix,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // running/degraded/stopped
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *Heartbeat) GetNowUnix() int64 {
	if x != nil {
		return x.NowUnix
	}
	return 0
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{3}
}

var File_api_agent_proto protoreflect.FileDescriptor

const file_api_agent_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/agent.proto\x12\x05agent\"\xa9\x01\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"3\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vassigned_id\x18\x01 \x01(\tR\n" +
	"assignedId\"\x90\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fstarted_unix\x18\x02 \x01(\x03R\vstartedUnix\x12\x19\n" +
	"\bnow_unix\x18\x03 \x01(\x03R\anowUnix\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\a\n" +
	"\x05Empty2}\n" +
	"\bSentinel\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x124\n" +
	"\x10StreamHeartbeats\x12\x10.agent.Heartbeat\x1a\f.agent.Empty(\x01B:Z8github.com/Space-Cowb0y/Palantir_v2/sentinel/api;agentpbb\x06proto3"

var (
	file_api_agent_proto_rawDescOnce sync.Once
	file_api_agent_proto_rawDescData []byte
)

func file_api_agent_proto_rawDescGZIP() []byte {
	file_api_agent_proto_rawDescOnce.Do(func() {
		file_api_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_proto_rawDesc), len(file_api_agent_proto_rawDesc)))
	})
	return file_api_agent_proto_rawDescData
}

var file_api_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: agent.RegisterRequest
	(*RegisterResponse)(nil), // 1: agent.RegisterResponse
	(*Heartbeat)(nil),        // 2: agent.Heartbeat
	(*Empty)(nil),            // 3: agent.Empty
}
var file_api_agent_proto_depIdxs = []int32{
	0, // 0: agent.Sentinel.Register:input_type -> agent.RegisterRequest
	2, // 1: agent.Sentinel.StreamHeartbeats:input_type -> agent.Heartbeat
	1, // 2: agent.Sentinel.Register:output_type -> agent.RegisterResponse
	3, // 3: agent.Sentinel.StreamHeartbeats:output_type -> agent.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_agent_proto_init() }
func file_api_agent_proto_init() {
	if File_api_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_proto_rawDesc), len(file_api_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agent_proto_goTypes,
		DependencyIndexes: file_api_agent_proto_depIdxs,
		MessageInfos:      file_api_agent_proto_msgTypes,
	}.Build()
	File_api_agent_proto = out.File
	file_api_agent_proto_goTypes = nil
	file_api_agent_proto_depIdxs = nil
}
